### PR TITLE
terms: update Cuvva's address

### PR DESCRIPTION
**Pull request by peterjcole**
Updates terms to Cuvva's new address

### CODE REVIEW

**Review by ei09010 — APPROVED** [review]

**Review by ei09010 — APPROVED** [review]
lgtm

**Review by temmietope — APPROVED** [review]

**Comment by brittonjg** [comment]
@peterjcole is there any reason not to merge this PR?

**Comment by peterjcole** [comment]
@brittonjg whoops - I was going to merge it, didn't have permissions, and then got derailed and forgot about it

Thread here: https://cuvva.slack.com/archives/CV6SZA1KN/p1710343630160039

I still don't have permission, are you able to merge it for me?

**Comment by brittonjg** [comment]
@peterjcole that's merged. I feel like there's a process to make this live. Are you able to own that?

**Pull request merged**
