### PR TITLE
Terms & conditions v1.5

### PR DESCRIPTION
**Pull request by robdaviescuvva**
I've suggested minor changes to reflect >1 motor underwriter, IPID, and minor TOV amendments

### CODE REVIEW

**Comment by robdaviescuvva** [comment]
@billinghamj

**Comment by billinghamj** [comment]
Looks great! Thanks @robdaviescuvva.

Will ask the backend team to arrange to release this. Need to:

- ensure there's no non-ASCII characters in there
- ensure consistent spacing, no trailing spaces, etc
- update the version, date & link in the footer (date _must_ be the day it actually appears in the app etc - be careful not to inadvertently backdate/forward date)
- merge and tag with the version

Example: 
https://github.com/cuvva/terms/commit/91d5a4cdd5278ca85988fecdca2cc24850b00745

**Comment by DuffleOne** [comment]
Can confirm:

- no non-ASCII characters
- no inconsistent spacing, double spaces, or trailing spaces

**Comment by DuffleOne** [comment]
Tagged the release, ready to merge now

**Pull request merged**
